### ISSUE TITLE
How about a large scale option?

### ISSUE THREAD

**Issue by purdy** [AlecM33/Werewolf#104]
What if you had a large group where you didn't know the number off-hand and instead, had people join and then the moderator starts the game when everyone has indicated they joined and the game doles out roles based on a percentage vs. a static number?

**Comment by AlecM33** [comment]
Hello!

The current design assumes that you will establish the player count before building the game. That's of course not the most flexible. So you're proposing that some algorithm figure out the roles in the game based on the player count? That might work if you heavily limit the set of roles to, for example, just villager, seer, werewolf, and hunter. But the app allows any number of custom roles for which you can't have hard-coded balancing. 

Your use-case could be served in other ways I think, such as allowing editing of the deck after the game has been created.

**Comment by purdy** [comment]
I was thinking in my case, I'd be running a very simple two role (villager and werewolf) game and have everyone join and then when everyone's in, the moderator starts it and the game randomly doles out the roles based on a percentage. But I think your deck editing feature could address this case better.

BTW, I just recently learned Express & Node, myself, and your repo is awesome! I love how it's setup with the GitHub action and lint checks, etc. Definitely helped me elevate my game! Big hat-tip to you!

**Comment by AlecM33** [comment]
I think the furthest I'd want to go on the auto-balancing side would be to do something like offer common game setups as templates that can be created immediately (Like villager-werewolf decks for 9, 11, 13 players etc.) Overall the priority is to make things as easy as possible for the host, and I've realized that if you create a game only to have someone drop that it can be a bit annoying, since you have to establish the deck before creating the game. So there's some thinking to do about how to mitigate or avoid that scenario. 

Thanks! I'm glad the codebase has been helpful to you. I definitely put more thought into how it's organized this time around.

**Comment by AlecM33** [comment]
I've really never gotten feedback from someone that has tried to use it with a larger group. My group has used it with up to 13 or so, and even then it can be tricky to get an accurate count of who is in/out. Re-creating the game isn't _too_ much trouble at least.

**Comment by purdy** [comment]
I'm going to close my own issue here because I think my use case is more of an edge case that can be supported with better planning.

Thanks again for a great repo & project!

**Comment by AlecM33** [comment]
> I'm going to close my own issue here because I think my use case is more of an edge case that can be supported with better planning.
> 
> Thanks again for a great repo & project!

Okay. Making things easier from a game creation perspective is always on my radar, though, so feel free to share any experiences you have using the application going forward. Thanks for stopping by!
