### ISSUE TITLE
Card flip does not work in Firefox

### ISSUE THREAD

**Issue by AlecM33** [AlecM33/Werewolf#31]
The back side of the card is visible, but reversed.

**Comment by rtmoffat** [comment]
Taking a look at this issue. I think it has something to do with transform-style: preserve-3d; not being interpreted consistently across browsers. If it's turned off in Chrome or Edge after the card is flipped, it exhibits the same behavior as Firefox, flipping the image without it changing to a grey box.
 
![ww_flip](https://user-images.githubusercontent.com/27305959/79891650-4e19bd00-83cf-11ea-92b5-88e912b08dd5.gif)

However, I'm not sure why it's flipping to a grey box at all. Is the expected behavior according to HTML standards within the context of this code to flip to a reverse of the image or a grey box? In other words, which browser is actually interpreting this code correctly?

However, I'm also wondering what the desired behavior should be. Currently in Chrome or Edge, it just flips to a grey box. Maybe it should flip to a game logo or some sort of "flipped" symbol or something instead? Might be more informative.

**Comment by AlecM33** [comment]
I personally think you are going down the wrong path here. I think the buggy behavior is related to the compatibility and behavior surrounding the `backface-visibility` CSS property (https://developer.mozilla.org/en-US/docs/Web/CSS/backface-visibility). Originally the flip only worked in Chrome, and I was able to fix it in Safari by adding a prefixed version of the rule: ` -webkit-backface-visibility: hidden;`

The Firefox issue lingers, but I'm betting there's some additional fix related to that. Was investigating but got pulled into more pressing issues, since nobody needs to flip their cards at present.
